name: Trigger auto deployment for container-app-jxeoz5clmmhne

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-jxeoz5clmmhne-AutoDeployTrigger-d3e7e4b4-1059-4e67-95e3-b31cf78a645b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPJXEOZ5CLMMHNE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPJXEOZ5CLMMHNE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPJXEOZ5CLMMHNE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryjxeoz5clmmhne.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPJXEOZ5CLMMHNE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJXEOZ5CLMMHNE_REGISTRY_PASSWORD }}
          containerAppName: container-app-jxeoz5clmmhne
          resourceGroup: vuebasic82d19988
          imageToBuild: containerregistryjxeoz5clmmhne.azurecr.io/container-app-jxeoz5clmmhne:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


